modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/sciwhiz12/SnowyWeaponry/issues"

[[mods]]
modId="snowyweaponry"
version="${file.jarVersion}"
displayName="Snowy Weaponry"
displayURL="https://github.com/sciwhiz12/SnowyWeaponry"
credits="To the wonderful folks at MMD for WinterJam"
authors="§esciwhiz12§r"
description='''
Adds different snow-based weaponry. (and snow cones!)

§oThis mod was an entry for §2MMD§r's §bWinterJam 2020§r.
'''

[[dependencies.snowyweaponry]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowyweaponry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
